version: '2'
services:
  instance:
    image: asynchronyringo/moodle:latest
    command: /usr/bin/internal_start.sh
    ports:
      - 3002:80
      - 3003:443
    volumes:
      - ./internal_start.sh:/usr/bin/internal_start.sh
      - ./moodle_data:/var/moodledata
      - ./config.php:/var/www/html/config.php
      # - ./spark_local:/var/www/html/local/spark
    env_file:
      - db.env
    depends_on:
      - db
  db:
    image: postgres:9.3
    volumes:
      - ./db_data:/var/lib/postgresql/data/
    env_file:
      - db.env
